apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpas.fullname" . }}-db-secret
  labels:
    {{- include "gpas.labels" . | nindent 4 }}
    app.kubernetes.io/component: gpas-db
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.secrets.rootPassword | quote }}
