apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpas.fullname" . }}-secret
  labels:
    {{- include "gpas.labels" . | nindent 4 }}
    app.kubernetes.io/component: gpas
type: Opaque
stringData:
  WF_ADMIN_PASS: {{ .Values.secrets.WF_ADMIN_PASS | quote }}
  WF_ADMIN_USER: {{ .Values.secrets.WF_ADMIN_USER | quote }}
