apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-secret
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required "redis.secrets.password is required" .Values.secrets.password | quote }}
