apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "redis.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "redis.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "redis.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsNonRoot: true
      containers:
        - name: redis
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - redis-server
          args:
            - --maxmemory
            - {{ .Values.maxmemory | quote }}
            - --maxmemory-policy
            - {{ .Values.maxmemoryPolicy | quote }}
            - --maxclients
            - {{ .Values.maxclients | quote }}
            - --appendonly
            - {{ .Values.appendonly | quote }}
            - --appendfsync
            - {{ .Values.appendfsync | quote }}
            - --auto-aof-rewrite-percentage
            - "100"
            - --auto-aof-rewrite-min-size
            - "64mb"
            - --requirepass
            - $(REDIS_PASSWORD)
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis.fullname" . }}-secret
                  key: password
          ports:
            - name: redis
              containerPort: {{ .Values.port }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - 'redis-cli -a "$REDIS_PASSWORD" --no-auth-warning ping'
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - 'redis-cli -a "$REDIS_PASSWORD" --no-auth-warning ping'
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
