apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-db.fullname" . }}-secret
  labels:
    {{- include "app-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.secrets.password | quote }}
  MEDANON_APP_DB_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.username .Values.secrets.password (include "app-db.fullname" .) (.Values.port | int) .Values.database | quote }}
