apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-db.fullname" . }}
  labels:
    {{- include "app-db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "app-db.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: {{ .Values.port }}
      targetPort: postgres
      protocol: TCP
