"""Page 7 — Synthetic Data: generate statistical synthetic FHIR Patient resources."""
import json
import os

import streamlit as st

from utils.api import generate_synthetic
from utils.sidebar import render_sidebar

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(page_title="Synthetic Data — MedAnon", layout="wide")
render_sidebar()

st.title("Synthetic Data")
st.info(
    "Workflow: de-identify real patient data first using Batch Processing, "
    "then upload the de-identified file here to generate synthetic patients "
    "that preserve statistical distributions without copying any real record."
)

with st.expander("How this works", expanded=False):
    st.markdown("""
**Why synthetic data?**

De-identified data still carries residual re-identification risk (see **Risk Assessment**).
Synthetic data goes a step further: new patient records are generated by sampling
from the statistical distributions of the input — gender ratios, birth year spread,
and zip prefix distribution — without copying any individual record.

**What is preserved:**
- Gender distribution (proportions of male/female/other)
- Birth year distribution (sampled from input years with +/-2-year jitter)
- Geographic distribution (3-digit zip prefix)

**What is NOT preserved:**
- Clinical data (conditions, medications, observations) — not present in output
- Exact ages or zip codes — jitter and prefix truncation are applied
- Any direct or indirect identifier

**Output format:** NDJSON — one synthetic FHIR Patient resource per line.
Each record is tagged with `meta.tag[code=SYN]` to identify it as synthetic.

**Use cases:** Algorithm testing, UI development, staff training, sharing with
external parties where even de-identified data cannot leave the organization.
""")

# ── Format → Content-Type map ─────────────────────────────────────────────────
_EXT_TO_CT = {
    ".ndjson": "application/x-ndjson",
    ".json":   "application/json",
    ".xml":    "application/fhir+xml",
}

# ── Input ─────────────────────────────────────────────────────────────────────
MAX_UPLOAD_BYTES = 10 * 1024 * 1024  # 10 MB

uploaded = st.file_uploader(
    "Upload de-identified FHIR file (NDJSON, JSON Bundle, or XML — Patient resources)",
    type=["ndjson", "json", "xml"],
    help="Max 10 MB. The file should contain de-identified Patient resources.",
)

upload_bytes: bytes | None = None
upload_ct: str = "application/x-ndjson"

if uploaded:
    if uploaded.size > MAX_UPLOAD_BYTES:
        st.error(f"File too large ({uploaded.size / 1024 / 1024:.1f} MB). Maximum is 10 MB.")
    else:
        upload_bytes = uploaded.read()
        ext = os.path.splitext(uploaded.name)[1].lower()
        upload_ct = _EXT_TO_CT.get(ext, "application/x-ndjson")

        raw_text = upload_bytes.decode("utf-8", errors="replace")
        if upload_ct == "application/x-ndjson":
            lines = [ln for ln in raw_text.splitlines() if ln.strip() and not ln.strip().startswith("//")]
            patient_lines = sum(
                1 for ln in lines
                if "Patient" in ln  # fast pre-filter before JSON parse
                and json.loads(ln).get("resourceType") == "Patient"
            )
            st.caption(
                f"{len(lines)} non-empty lines loaded from **{uploaded.name}** "
                f"({patient_lines} Patient resource(s) detected)"
            )
        elif upload_ct == "application/fhir+xml":
            st.caption(f"{len(upload_bytes):,} bytes loaded from **{uploaded.name}** (XML)")
        else:
            try:
                parsed = json.loads(raw_text)
                if isinstance(parsed, dict) and parsed.get("resourceType") == "Bundle":
                    entry_count = len(parsed.get("entry", []))
                    st.caption(f"Bundle with {entry_count} entries loaded from **{uploaded.name}**")
                else:
                    st.caption(f"JSON resource loaded from **{uploaded.name}**")
            except Exception:
                st.caption(f"{len(upload_bytes):,} bytes loaded from **{uploaded.name}**")

# ── Generation parameters ──────────────────────────────────────────────────────
st.markdown("---")
col_count, col_seed = st.columns([2, 1])

with col_count:
    count = st.slider(
        "Number of synthetic patients to generate",
        min_value=1,
        max_value=10000,
        value=100,
        step=1,
        help="How many synthetic Patient records to produce.",
    )

with col_seed:
    use_seed = st.checkbox("Fix random seed (reproducible output)", value=False)
    seed_value: int | None = None
    if use_seed:
        seed_value = st.number_input("Seed", min_value=0, max_value=2**31 - 1, value=42, step=1)

if st.button(
    "Generate Synthetic Data",
    type="primary",
    disabled=not upload_bytes,
):
    with st.spinner(f"Generating {count} synthetic patients…"):
        ok, result_bytes = generate_synthetic(
            upload_bytes,
            count=count,
            content_type=upload_ct,
            seed=int(seed_value) if use_seed and seed_value is not None else None,
        )

    if not ok:
        try:
            err = result_bytes.decode("utf-8", errors="replace")
        except Exception:
            err = str(result_bytes)
        st.error(f"Error from server: {err}")
        st.stop()

    st.session_state["synthetic_bytes"] = result_bytes
    st.session_state["synthetic_count"] = count

# ── Results ───────────────────────────────────────────────────────────────────
if "synthetic_bytes" in st.session_state:
    result_bytes: bytes = st.session_state["synthetic_bytes"]
    generated_count: int = st.session_state["synthetic_count"]

    lines = [ln for ln in result_bytes.decode("utf-8", errors="replace").splitlines() if ln.strip()]
    st.success(f"Generated {len(lines)} synthetic Patient resource(s).")

    col_dl, col_info = st.columns([1, 2])
    with col_dl:
        st.download_button(
            label="Download NDJSON",
            data=result_bytes,
            file_name="synthetic_patients.ndjson",
            mime="application/x-ndjson",
        )
    with col_info:
        st.caption(
            f"{len(result_bytes):,} bytes · {len(lines)} records · "
            "each tagged `meta.tag[code=SYN]`"
        )

    if lines:
        with st.expander("Preview first 3 records"):
            for ln in lines[:3]:
                try:
                    st.json(json.loads(ln))
                except Exception:
                    st.code(ln)
