apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worker.fullname" . }}-secret
  labels:
    {{- include "worker.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
type: Opaque
stringData:
  MEDANON_HASH_KEY: {{ .Values.secrets.MEDANON_HASH_KEY | quote }}
  GPAS_BASIC_USER: {{ .Values.secrets.GPAS_BASIC_USER | quote }}
  GPAS_BASIC_PASS: {{ .Values.secrets.GPAS_BASIC_PASS | quote }}
  {{- if .Values.secrets.MEDANON_APP_DB_URL }}
  MEDANON_APP_DB_URL: {{ .Values.secrets.MEDANON_APP_DB_URL | quote }}
  {{- end }}
  {{- if .Values.secrets.MEDANON_REDIS_URL }}
  MEDANON_REDIS_URL: {{ .Values.secrets.MEDANON_REDIS_URL | quote }}
  {{- end }}
