-- =========================================================================
-- gPAS Notification Service schema  PostgreSQL 16
--
-- Translated from MySQL 8.0 original (services/gpas/sqls/01_create_database_noti.sql).
-- Lives in the "notification_service" schema within the gpas database.
-- =========================================================================

CREATE SCHEMA IF NOT EXISTS notification_service;
SET search_path TO notification_service;

-- ── Tables ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS configuration (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activated   BOOLEAN DEFAULT NULL,
    "configKey" VARCHAR(255) NOT NULL,
    description TEXT,
    value       TEXT,
    CONSTRAINT "UK_configKey" UNIQUE ("configKey")
);

-- Seed default configuration row
INSERT INTO configuration (activated, "configKey", description, value) VALUES
    (true, 'notification.config', NULL,
     '<org.emau.icmvc.ttp.notification.service.model.config.NotificationConfig>
    <consumerConfigs>
        <param>
            <key>Dispatcher</key>
            <value class="org.emau.icmvc.ttp.notification.service.model.config.ConsumerConfig">
                <connectionType>EJB</connectionType>
                <messageTypes>
                    <string>EPIX.AssignIdentity</string>
                </messageTypes>
                <excludeClientIdFilter class="set">
                    <string>gICS_Web</string>
                </excludeClientIdFilter>
                <parameter>
                    <param>
                        <key>ejb.jndi.url</key>
                        <value>java:global/test-dispatcher-ear-1.15.3/dispatcher-services-1.15.3/InternalNotificationConsumer</value>
                    </param>
                </parameter>
            </value>
        </param>
        <param>
            <key>HTTPConsumer</key>
            <value class="org.emau.icmvc.ttp.notification.service.model.config.ConsumerConfig">
                <connectionType>HTTP</connectionType>
                <messageTypes>
                    <string>GICS.exampleMethodWithNotification</string>
                </messageTypes>
                <excludeClientIdFilter class="set">
                    <string>E-PIX_Web</string>
                </excludeClientIdFilter>
                <parameter>
                    <param>
                        <key>url</key>
                        <value>https://httpbin.org/post</value>
                    </param>
                    <param>
                        <key>username</key>
                        <value>pp</value>
                    </param>
                    <param>
                        <key>passwort</key>
                        <value>pwd</value>
                    </param>
                </parameter>
            </value>
        </param>
    </consumerConfigs>
</org.emau.icmvc.ttp.notification.service.model.config.NotificationConfig>')
ON CONFLICT ("configKey") DO NOTHING;

CREATE TABLE IF NOT EXISTS notifications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id    VARCHAR(255) NOT NULL,
    consumer_id  VARCHAR(255) NOT NULL,
    "creationDate" TIMESTAMP NOT NULL,
    data         TEXT NOT NULL,
    send_date    TIMESTAMP DEFAULT NULL,
    status       VARCHAR(255) DEFAULT NULL,
    type         VARCHAR(255) NOT NULL,
    error_message TEXT
);

-- "sequence" is a PostgreSQL reserved word  must be quoted
CREATE TABLE IF NOT EXISTS "sequence" (
    "SEQ_NAME"   VARCHAR(50) NOT NULL PRIMARY KEY,
    "SEQ_COUNT"  NUMERIC(38,0) DEFAULT NULL
);

-- Seed sequence counter
INSERT INTO "sequence" ("SEQ_NAME", "SEQ_COUNT") VALUES ('SEQ_GEN', 0)
ON CONFLICT ("SEQ_NAME") DO NOTHING;


-- ── Database role ──────────────────────────────────────────────────────────

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'noti_user') THEN
        CREATE ROLE noti_user LOGIN PASSWORD 'noti_password';
    END IF;
END
$$;
GRANT USAGE ON SCHEMA notification_service TO noti_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA notification_service TO noti_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA notification_service TO noti_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA notification_service GRANT ALL ON TABLES TO noti_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA notification_service GRANT ALL ON SEQUENCES TO noti_user;

-- Reset search_path
SET search_path TO public;
