{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "anonymizer.fullname" . }}
  labels:
    {{- include "anonymizer.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "anonymizer.selectorLabels" (dict "Release" .Release "component" "anonymizer") | nindent 6 }}
{{- end }}
