apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anonymizer.fullname" . }}-secret
  labels:
    {{- include "anonymizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: anonymizer
type: Opaque
stringData:
  MEDANON_HASH_KEY: {{ .Values.secrets.MEDANON_HASH_KEY | quote }}
  GPAS_BASIC_USER: {{ .Values.secrets.GPAS_BASIC_USER | quote }}
  GPAS_BASIC_PASS: {{ .Values.secrets.GPAS_BASIC_PASS | quote }}
  GPAS_TOKEN: {{ .Values.secrets.GPAS_TOKEN | quote }}
  {{- if .Values.secrets.MEDANON_APP_DB_URL }}
  MEDANON_APP_DB_URL: {{ .Values.secrets.MEDANON_APP_DB_URL | quote }}
  {{- end }}
  {{- if .Values.secrets.MEDANON_REDIS_URL }}
  MEDANON_REDIS_URL: {{ .Values.secrets.MEDANON_REDIS_URL | quote }}
  {{- end }}
  {{- if .Values.secrets.NLP_REDIS_URL }}
  NLP_REDIS_URL: {{ .Values.secrets.NLP_REDIS_URL | quote }}
  {{- end }}
  {{- if .Values.secrets.rsaPublicKey }}
  id_rsa.pub: {{ .Values.secrets.rsaPublicKey | quote }}
  {{- end }}
  {{- if .Values.secrets.rsaPrivateKey }}
  id_rsa: {{ .Values.secrets.rsaPrivateKey | quote }}
  {{- end }}
