-- PostgreSQL port of the gRAS (gPAS web-UI auth) schema.
--
-- MySQL used a separate `gras` database; here it is a schema inside the
-- single "gpas" Postgres database (grasDS connects with
-- ?currentSchema=gras, see services/gpas/jboss_pg/configure_wildfly_gras.cli),
-- authenticating as the same role as everything else (gpas_user, per
-- TTP_DB_USER in docker-compose.yml) - there is no separate gras_user role.
--
-- This schema backs the elytron JdbcRealm (TtpRealm) that gpas-web's login
-- form authenticates against, querying the domainuser_password /
-- domainuser_role views defined below. Without this file, nobody can log
-- into the gPAS web UI at all.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS gras;
-- "public" stays on the path so pgcrypto's digest() (installed there) remains visible.
SET search_path TO gras, public;

CREATE TABLE IF NOT EXISTS domain (
    name VARCHAR(255) NOT NULL DEFAULT '',
    description VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS project (
    name VARCHAR(255) NOT NULL DEFAULT '',
    description VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS group_ (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL DEFAULT '',
    project_name VARCHAR(255) NOT NULL DEFAULT '',
    description VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY (id),
    CONSTRAINT unique_name_project UNIQUE (name, project_name),
    CONSTRAINT fk_project_group FOREIGN KEY (project_name) REFERENCES project (name)
);

CREATE TABLE IF NOT EXISTS role (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL DEFAULT '',
    project_name VARCHAR(255) NOT NULL DEFAULT '',
    description VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY (id),
    CONSTRAINT unique_role_name UNIQUE (name),
    CONSTRAINT fk_project_role FOREIGN KEY (project_name) REFERENCES project (name)
);

CREATE TABLE IF NOT EXISTS group_role_mapping (
    group_id INT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (group_id, role_id),
    CONSTRAINT fk_group FOREIGN KEY (group_id) REFERENCES group_ (id) ON DELETE CASCADE,
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES role (id)
);

CREATE TABLE IF NOT EXISTS "user" (
    name VARCHAR(255) NOT NULL DEFAULT '',
    password VARCHAR(255),
    active SMALLINT DEFAULT 1,
    description VARCHAR(255) NOT NULL DEFAULT '',
    email VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS permission (
    group_id INT NOT NULL,
    user_name VARCHAR(255) NOT NULL DEFAULT '',
    domain_name VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY (group_id, user_name, domain_name),
    CONSTRAINT fk_permission_domain FOREIGN KEY (domain_name) REFERENCES domain (name),
    CONSTRAINT fk_permission_group FOREIGN KEY (group_id) REFERENCES group_ (id),
    CONSTRAINT fk_permission_user FOREIGN KEY (user_name) REFERENCES "user" (name)
);

CREATE TABLE IF NOT EXISTS hist_domain (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    "timestamp" TIMESTAMP NOT NULL,
    action VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hist_group_ (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    group_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    project_name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    "timestamp" TIMESTAMP NOT NULL,
    action VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hist_group_role_mapping (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    group_id VARCHAR(255) NOT NULL,
    role_id VARCHAR(255) NOT NULL,
    "timestamp" TIMESTAMP NOT NULL,
    action VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hist_permission (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    group_id INT NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    domain_name VARCHAR(255) NOT NULL,
    "timestamp" TIMESTAMP NOT NULL,
    action VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hist_project (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    "timestamp" TIMESTAMP NOT NULL,
    action VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hist_role (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    role_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    project_name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    "timestamp" TIMESTAMP NOT NULL,
    action VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hist_user (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL DEFAULT '',
    password VARCHAR(255),
    active SMALLINT DEFAULT 1,
    description VARCHAR(255) NOT NULL DEFAULT '',
    email VARCHAR(255) NOT NULL DEFAULT '',
    "timestamp" TIMESTAMP NOT NULL,
    action VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Views backing the elytron JdbcRealm (TtpRealm) login query - see
-- services/gpas/jboss_pg/configure_wildfly_gras.cli's principal-query.
CREATE OR REPLACE VIEW domainuser_password AS
    SELECT DISTINCT CONCAT_WS('@', p.user_name, p.domain_name) AS domainuser, u.password AS password
    FROM permission p JOIN "user" u ON u.name = p.user_name
    WHERE u.active = 1;

CREATE OR REPLACE VIEW domainuser_role AS
    SELECT DISTINCT CONCAT_WS('@', p.user_name, p.domain_name) AS domainuser, r.name AS role
    FROM permission p
        JOIN group_role_mapping m ON p.group_id = m.group_id
        JOIN role r ON m.role_id = r.id
        JOIN "user" u ON u.name = p.user_name
    WHERE u.active = 1;

CREATE OR REPLACE VIEW validate AS
    SELECT DISTINCT a.domainuser AS domainuser, a.password AS password, b.role AS role
    FROM domainuser_password a JOIN domainuser_role b ON a.domainuser = b.domainuser;

-- *** audit-history + referential-cleanup triggers ***
-- BEFORE DELETE/UPDATE triggers that both log to the hist_* tables and
-- (for delete) cascade-clean dependent rows, mirroring the MySQL originals.

CREATE OR REPLACE FUNCTION gras_delete_domain() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_domain (name, description, "timestamp", action)
        VALUES (OLD.name, OLD.description, now(), 'delete');
    DELETE FROM permission WHERE domain_name = OLD.name;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS delete_domain ON domain;
CREATE TRIGGER delete_domain BEFORE DELETE ON domain
    FOR EACH ROW EXECUTE FUNCTION gras_delete_domain();

CREATE OR REPLACE FUNCTION gras_delete_group() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_group_ (group_id, name, project_name, description, "timestamp", action)
        VALUES (OLD.id, OLD.name, OLD.project_name, OLD.description, now(), 'delete');
    DELETE FROM group_role_mapping WHERE group_id = OLD.id;
    DELETE FROM permission WHERE group_id = OLD.id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS delete_group ON group_;
CREATE TRIGGER delete_group BEFORE DELETE ON group_
    FOR EACH ROW EXECUTE FUNCTION gras_delete_group();

CREATE OR REPLACE FUNCTION gras_delete_group_role_mapping() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_group_role_mapping (group_id, role_id, "timestamp", action)
        VALUES (OLD.group_id, OLD.role_id, now(), 'delete');
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS delete_group_role_mapping ON group_role_mapping;
CREATE TRIGGER delete_group_role_mapping BEFORE DELETE ON group_role_mapping
    FOR EACH ROW EXECUTE FUNCTION gras_delete_group_role_mapping();

CREATE OR REPLACE FUNCTION gras_delete_permission() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_permission (group_id, user_name, domain_name, "timestamp", action)
        VALUES (OLD.group_id, OLD.user_name, OLD.domain_name, now(), 'delete');
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS delete_permission ON permission;
CREATE TRIGGER delete_permission BEFORE DELETE ON permission
    FOR EACH ROW EXECUTE FUNCTION gras_delete_permission();

CREATE OR REPLACE FUNCTION gras_delete_project() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_project (name, description, "timestamp", action)
        VALUES (OLD.name, OLD.description, now(), 'delete');
    DELETE FROM group_ WHERE project_name = OLD.name;
    DELETE FROM role WHERE project_name = OLD.name;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS delete_project ON project;
CREATE TRIGGER delete_project BEFORE DELETE ON project
    FOR EACH ROW EXECUTE FUNCTION gras_delete_project();

CREATE OR REPLACE FUNCTION gras_delete_role() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_role (role_id, name, project_name, description, "timestamp", action)
        VALUES (OLD.id, OLD.name, OLD.project_name, OLD.description, now(), 'delete');
    DELETE FROM group_role_mapping WHERE role_id = OLD.id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS delete_role ON role;
CREATE TRIGGER delete_role BEFORE DELETE ON role
    FOR EACH ROW EXECUTE FUNCTION gras_delete_role();

CREATE OR REPLACE FUNCTION gras_delete_user() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_user (name, password, active, description, email, "timestamp", action)
        VALUES (OLD.name, OLD.password, OLD.active, OLD.description, OLD.email, now(), 'delete');
    DELETE FROM permission WHERE user_name = OLD.name;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS delete_user ON "user";
CREATE TRIGGER delete_user BEFORE DELETE ON "user"
    FOR EACH ROW EXECUTE FUNCTION gras_delete_user();

CREATE OR REPLACE FUNCTION gras_insert_group_role_mapping() RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM role r, group_ g
        WHERE r.id = NEW.role_id AND g.id = NEW.group_id AND g.project_name = r.project_name
    ) THEN
        RAISE EXCEPTION 'Role and Group have to belong to the same Project';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS insert_group_role_mapping ON group_role_mapping;
CREATE TRIGGER insert_group_role_mapping BEFORE INSERT ON group_role_mapping
    FOR EACH ROW EXECUTE FUNCTION gras_insert_group_role_mapping();

CREATE OR REPLACE FUNCTION gras_update_domain() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_domain (name, description, "timestamp", action)
        VALUES (OLD.name, OLD.description, now(), 'update');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_domain ON domain;
CREATE TRIGGER update_domain BEFORE UPDATE ON domain
    FOR EACH ROW EXECUTE FUNCTION gras_update_domain();

CREATE OR REPLACE FUNCTION gras_update_group() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_group_ (group_id, name, project_name, description, "timestamp", action)
        VALUES (OLD.id, OLD.name, OLD.project_name, OLD.description, now(), 'update');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_group ON group_;
CREATE TRIGGER update_group BEFORE UPDATE ON group_
    FOR EACH ROW EXECUTE FUNCTION gras_update_group();

CREATE OR REPLACE FUNCTION gras_update_group_role_mapping() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_group_role_mapping (group_id, role_id, "timestamp", action)
        VALUES (OLD.group_id, OLD.role_id, now(), 'update');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_group_role_mapping ON group_role_mapping;
CREATE TRIGGER update_group_role_mapping BEFORE UPDATE ON group_role_mapping
    FOR EACH ROW EXECUTE FUNCTION gras_update_group_role_mapping();

CREATE OR REPLACE FUNCTION gras_update_permission() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_permission (group_id, user_name, domain_name, "timestamp", action)
        VALUES (OLD.group_id, OLD.user_name, OLD.domain_name, now(), 'update');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_permission ON permission;
CREATE TRIGGER update_permission BEFORE UPDATE ON permission
    FOR EACH ROW EXECUTE FUNCTION gras_update_permission();

CREATE OR REPLACE FUNCTION gras_update_project() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_project (name, description, "timestamp", action)
        VALUES (OLD.name, OLD.description, now(), 'update');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_project ON project;
CREATE TRIGGER update_project BEFORE UPDATE ON project
    FOR EACH ROW EXECUTE FUNCTION gras_update_project();

CREATE OR REPLACE FUNCTION gras_update_role() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_role (role_id, name, project_name, description, "timestamp", action)
        VALUES (OLD.id, OLD.name, OLD.project_name, OLD.description, now(), 'update');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_role ON role;
CREATE TRIGGER update_role BEFORE UPDATE ON role
    FOR EACH ROW EXECUTE FUNCTION gras_update_role();

CREATE OR REPLACE FUNCTION gras_update_user() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO hist_user (name, password, active, description, email, "timestamp", action)
        VALUES (OLD.name, OLD.password, OLD.active, OLD.description, OLD.email, now(), 'update');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_user ON "user";
CREATE TRIGGER update_user BEFORE UPDATE ON "user"
    FOR EACH ROW EXECUTE FUNCTION gras_update_user();

-- *** comfort procedures (called from 02_init_database_gras_for_gpas.sql) ***

CREATE OR REPLACE PROCEDURE createDomain(IN domainName VARCHAR(255), IN description VARCHAR(255))
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO domain (name, description) VALUES (domainName, description)
        ON CONFLICT (name) DO NOTHING;
END;
$$;

CREATE OR REPLACE PROCEDURE createProject(IN projectName VARCHAR(255), IN description VARCHAR(255))
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO project (name, description) VALUES (projectName, description)
        ON CONFLICT (name) DO NOTHING;
END;
$$;

CREATE OR REPLACE PROCEDURE disableUser(IN userName VARCHAR(255))
LANGUAGE plpgsql AS $$
BEGIN
    UPDATE "user" SET active = 0 WHERE name = userName;
END;
$$;

CREATE OR REPLACE PROCEDURE enableUser(IN userName VARCHAR(255))
LANGUAGE plpgsql AS $$
BEGIN
    UPDATE "user" SET active = 1 WHERE name = userName;
END;
$$;

CREATE OR REPLACE PROCEDURE changePassword(IN userName VARCHAR(255), IN newPassword VARCHAR(255))
LANGUAGE plpgsql
SET search_path = gras, public
AS $$
BEGIN
    UPDATE "user" SET password = encode(digest(newPassword::bytea, 'sha256'), 'hex') WHERE name = userName;
END;
$$;

CREATE OR REPLACE PROCEDURE createUser(IN userName VARCHAR(255), IN password VARCHAR(255), IN description VARCHAR(255))
LANGUAGE plpgsql
SET search_path = gras, public
AS $$
BEGIN
    INSERT INTO "user" (name, password, active, description)
        VALUES (userName, encode(digest(password::bytea, 'sha256'), 'hex'), 1, description)
        ON CONFLICT (name) DO NOTHING;
END;
$$;

CREATE OR REPLACE PROCEDURE createGroup(IN projectName VARCHAR(255), IN groupName VARCHAR(255), IN description VARCHAR(255))
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO group_ (name, project_name, description) VALUES (groupName, projectName, description)
        ON CONFLICT (name, project_name) DO NOTHING;
END;
$$;

CREATE OR REPLACE PROCEDURE createRole(IN projectName VARCHAR(255), IN roleName VARCHAR(255), IN description VARCHAR(255))
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO role (name, project_name, description) VALUES (roleName, projectName, description)
        ON CONFLICT (name) DO NOTHING;
END;
$$;

CREATE OR REPLACE PROCEDURE createGroupRoleMapping(IN projectName VARCHAR(255), IN groupName VARCHAR(255), IN roleName VARCHAR(255))
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO group_role_mapping (group_id, role_id) VALUES (
        (SELECT id FROM group_ WHERE name = groupName AND project_name = projectName),
        (SELECT id FROM role WHERE name = roleName)
    ) ON CONFLICT (group_id, role_id) DO NOTHING;
END;
$$;

CREATE OR REPLACE PROCEDURE grantAdminRights(IN domainName VARCHAR(255), IN projectName VARCHAR(255), IN userName VARCHAR(255))
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO permission (group_id, user_name, domain_name)
        SELECT DISTINCT id, userName, domainName FROM group_ WHERE project_name = projectName
        ON CONFLICT (group_id, user_name, domain_name) DO NOTHING;
END;
$$;

CREATE OR REPLACE PROCEDURE grantStandardRights(IN domainName VARCHAR(255), IN projectName VARCHAR(255), IN userName VARCHAR(255))
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM permission p USING group_ g
        WHERE p.group_id = g.id AND p.user_name = userName AND p.domain_name = domainName AND g.project_name = projectName;
    INSERT INTO permission (group_id, user_name, domain_name)
        SELECT DISTINCT id, userName, domainName FROM group_
        WHERE project_name = projectName AND name !~ '[aA]dmin';
END;
$$;

-- Manual credential-check helper (not called by the deployed app - the
-- elytron JdbcRealm queries the views above directly). Kept as a function
-- since Postgres procedures cannot return a result set the way MySQL's could.
CREATE OR REPLACE FUNCTION testCredetials(userName VARCHAR(255), passwd VARCHAR(255))
RETURNS TABLE (roles VARCHAR)
LANGUAGE sql
SET search_path = gras, public
AS $$
    SELECT DISTINCT r.name AS roles
    FROM permission p
        JOIN group_role_mapping m ON p.group_id = m.group_id
        JOIN role r ON m.role_id = r.id
        JOIN "user" u ON u.name = p.user_name AND u.active = 1
    WHERE CONCAT_WS('@', p.user_name, p.domain_name) = userName
        AND u.password = encode(digest(passwd::bytea, 'sha256'::text), 'hex');
$$;

RESET search_path;
