import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import {
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
} from '@/components/ui/collapsible';
import { Sparkles, ChevronDown, AlertCircle, Loader2, WifiOff, Database, Wand2 } from 'lucide-react';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';
import { type LocalRule, parseYamlIntoRules } from './configConstants';
import { generateConfig } from '@/api/agents';

// Maps the backend `source` field to user-friendly metadata.
const SOURCE_META: Record<string, { label: string; color: string; icon: React.ReactNode; tip: string }> = {
  ai: {
    label: 'AI generated',
    color: 'bg-[#0072bc]/10 text-[#0072bc] border-[#0072bc]/30',
    icon: <Sparkles className="size-3" />,
    tip: 'Rules were generated by the Ollama LLM on the configured AI VM.',
  },
  fallback: {
    label: 'Bundled profile',
    color: 'bg-amber-50 text-amber-700 border-amber-200',
    icon: <Database className="size-3" />,
    tip: 'AI was unreachable — a bundled profile was matched from your keyword (e.g. "HIPAA", "GDPR").',
  },
  heuristic: {
    label: 'Heuristic (no AI)',
    color: 'bg-violet-50 text-violet-700 border-violet-200',
    icon: <Wand2 className="size-3" />,
    tip: 'AI was unreachable and no profile keyword matched — rules were inferred from FHIRPath patterns and PHI keywords in your prompt.',
  },
};

// ---------------------------------------------------------------------------
// AiGeneratePanel -- describe what you need, AI generates rules
// ---------------------------------------------------------------------------

export function AiGeneratePanel({
  onImport,
}: {
  onImport: (rules: LocalRule[]) => void;
}) {
  const [open, setOpen] = useState(false);
  const [prompt, setPrompt] = useState('');
  const [regulation, setRegulation] = useState('');
  const [generating, setGenerating] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [lastSource, setLastSource] = useState<string | null>(null);

  const handleGenerate = async () => {
    setErr(null);
    if (prompt.trim().length < 10) {
      setErr('Please describe your requirements in at least 10 characters.');
      return;
    }
    setGenerating(true);
    try {
      const res = await generateConfig({ prompt: prompt.trim(), regulation: regulation.trim() || undefined });

      if (!res.yaml) {
        setErr('AI returned an empty configuration. Try rephrasing your prompt.');
        return;
      }

      const { rules: parsed, error: parseErr } = parseYamlIntoRules(res.yaml);
      if (parseErr) {
        setErr(parseErr);
        return;
      }

      onImport(parsed);
      setPrompt('');
      setRegulation('');
      setLastSource(res.source);
      setOpen(false);

      const src = SOURCE_META[res.source] ?? SOURCE_META.fallback;
      toast.success(
        `Generated ${parsed.length} rule${parsed.length !== 1 ? 's' : ''} — ${src.label}.${!res.valid ? ' Note: validation warnings detected.' : ''}`,
      );
    } catch (e) {
      setErr(String(e));
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Collapsible open={open} onOpenChange={setOpen}>
      <CollapsibleTrigger className="inline-flex h-7 items-center gap-1.5 rounded-md border bg-background px-2.5 text-xs font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground">
        <Sparkles className="size-3" />
        Generate with AI
        <ChevronDown className={cn('size-3 transition-transform', open && 'rotate-180')} />
      </CollapsibleTrigger>
      <CollapsibleContent className="mt-2">
        <div className="rounded-lg border bg-muted/30 p-3 space-y-2">
          <p className="text-xs text-muted-foreground">
            Describe your de-identification requirements in plain language. Rules are generated by the
            configured AI model. If the AI VM is unreachable, a bundled profile is matched from
            keywords like <span className="font-medium">HIPAA</span>, <span className="font-medium">GDPR</span>,
            or <span className="font-medium">research</span> — or rules are inferred directly from
            FHIRPath and PHI keywords in your prompt.
          </p>

          {/* Last-generation source badge */}
          {lastSource && (() => {
            const src = SOURCE_META[lastSource] ?? SOURCE_META.fallback;
            return (
              <div className={cn(
                'flex items-center gap-1.5 rounded-md border px-2.5 py-1.5 text-[11px] font-medium',
                src.color,
              )}>
                {src.icon}
                <span>{src.label}</span>
                <span className="opacity-60">·</span>
                <span className="font-normal">{src.tip}</span>
              </div>
            );
          })()}

          {/* Offline hint when AI is likely down */}
          {!generating && lastSource && lastSource !== 'ai' && (
            <div className="flex items-center gap-1.5 rounded-md border border-amber-200 bg-amber-50 px-2.5 py-1.5 text-[11px] text-amber-700">
              <WifiOff className="size-3 shrink-0" />
              AI model unreachable — last generation used the offline fallback.
              Check <span className="font-mono">MEDANON_AI_API_BASE</span> and
              that Ollama is listening on the remote VM.
            </div>
          )}
          <Textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="e.g. I need HIPAA Safe Harbor compliant de-identification that redacts patient names, hashes IDs for linkage, and generalizes dates to year only..."
            className="h-28 resize-none text-xs"
            disabled={generating}
          />
          <div>
            <label className="mb-1 block text-xs text-muted-foreground">
              Target regulation (optional)
            </label>
            <Input
              value={regulation}
              onChange={(e) => setRegulation(e.target.value)}
              placeholder="e.g. HIPAA, GDPR, HIPAA Safe Harbor"
              className="text-xs"
              disabled={generating}
            />
          </div>
          {err && (
            <p className="flex items-center gap-1 text-xs text-destructive">
              <AlertCircle className="size-3 shrink-0" /> {err}
            </p>
          )}
          <div className="flex gap-2">
            <Button
              size="sm"
              className="h-7 text-xs"
              onClick={handleGenerate}
              disabled={generating || !prompt.trim()}
            >
              {generating && <Loader2 className="size-3 animate-spin" />}
              {generating ? 'Generating...' : 'Generate Rules'}
            </Button>
            <Button
              variant="ghost"
              size="sm"
              className="h-7 text-xs"
              onClick={() => setOpen(false)}
              disabled={generating}
            >
              Cancel
            </Button>
          </div>
        </div>
      </CollapsibleContent>
    </Collapsible>
  );
}
