apiVersion: v1
kind: Service
metadata:
  name: {{ include "fhir-server.fullname" . }}
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: fhir-server
spec:
  type: ClusterIP
  selector:
    {{- include "fhir-server.selectorLabels" (dict "Release" .Release "component" "fhir-server") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
