import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar is organised around the Diátaxis framework. Each top-level
 * category maps to one of the four documentation modes. Pages are
 * auto-discovered from the folder structure so adding a Markdown file to a
 * quadrant folder lists it automatically (ordering via _category_.json +
 * sidebar_position frontmatter).
 */
const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'methodology',
    {
      type: 'category',
      label: 'Tutorials',
      link: {type: 'generated-index', description: 'Learning-oriented, step-by-step lessons that get you to a first working result.'},
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
    {
      type: 'category',
      label: 'How-to Guides',
      link: {type: 'generated-index', description: 'Task-oriented recipes for getting a specific job done.'},
      items: [{type: 'autogenerated', dirName: 'how-to'}],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {type: 'generated-index', description: 'Information-oriented, factual descriptions of the API, configuration, and components.'},
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Explanation',
      link: {type: 'generated-index', description: 'Understanding-oriented discussion of how and why the system works.'},
      items: [{type: 'autogenerated', dirName: 'explanation'}],
    },
  ],
};

export default sidebars;
