apiVersion: v2
name: fhir-server
description: "HAPI FHIR R4 server  H2 (default) or PostgreSQL database backend."
type: application
version: 0.1.0
appVersion: "v7.6.0"
keywords:
  - fhir
  - hapi
  - healthcare
