name: Helm Lint
on:
  push:
    paths: ["helm/**"]
  pull_request:
    paths: ["helm/**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - run: helm lint ./helm/medanon
